name: main
on:
  schedule:
    - cron: "10 0 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ${{matrix.os}}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]
    steps:
      - uses: actions/checkout@v3

      - name: Test Run 
        run: echo "Hello, World!"

      - name: Install ts-node 
        run: npm install ts-node  
      
      - name: Run NodeJS Puppeteer
        run: ts-node index.ts 